const area=document.querySelector('#game-area'),basket=document.querySelector('#basket'),overlay=document.querySelector('#overlay'),button=document.querySelector('#start-button'),scoreEl=document.querySelector('#score'),timeEl=document.querySelector('#time'),bestEl=document.querySelector('#best');
const gameImages=['ảnh áo trắng.jpg','ảnh ssid.jpg','ảnh polo.jpg','áo xa lánh.jpg','cute vl.jpg'];
let score=0,time=60,basketX=50,playing=false,stars=[],spawnTimer,gameTimer,animationId;let best=Number(localStorage.getItem('star-catcher-best')||0);bestEl.textContent=best;
function moveBasket(percent){basketX=Math.max(6,Math.min(94,percent));basket.style.left=`${basketX}%`;}
function makeStar(){const star=document.createElement('img');star.className='star';star.src=encodeURI(gameImages[Math.floor(Math.random()*gameImages.length)]);star.alt='Ảnh vật phẩm';const item={el:star,x:5+Math.random()*86,y:-55,speed:2.1+Math.random()*2.5};star.style.left=`${item.x}%`;area.append(star);stars.push(item);}
function gameLoop(){if(!playing)return;const h=area.clientHeight;stars=stars.filter(item=>{item.y+=item.speed;item.el.style.transform=`translateY(${item.y}px) rotate(${item.y*2}deg)`;const catchIt=item.y>h-105&&item.y<h-35&&Math.abs(item.x-basketX)<10;if(catchIt){item.el.remove();score++;scoreEl.textContent=score;return false;}if(item.y>h){item.el.remove();return false;}return true;});animationId=requestAnimationFrame(gameLoop);}
function finish(){playing=false;clearInterval(spawnTimer);clearInterval(gameTimer);cancelAnimationFrame(animationId);stars.forEach(item=>item.el.remove());stars=[];best=Math.max(best,score);localStorage.setItem('star-catcher-best',best);bestEl.textContent=best;const reward=score>100?`<div class="reward"><span class="trophy">🏆</span><b>Chúc mừng! Bạn nhận được cúp và phần thưởng bí mật.</b><img class="reward-image" src="${encodeURI(gameImages[Math.floor(Math.random()*gameImages.length)])}" alt="Phần thưởng ngẫu nhiên"></div>`:'';overlay.innerHTML=`<h2>Hết giờ! 🎉</h2><p>Bạn đã hứng được <b>${score} vật phẩm</b>.</p>${reward}<button>Chơi lại</button>`;overlay.classList.remove('hidden');overlay.querySelector('button').addEventListener('click',start);}
function start(){score=0;time=60;scoreEl.textContent=score;timeEl.textContent=time;overlay.classList.add('hidden');playing=true;area.focus();spawnTimer=setInterval(makeStar,620);gameTimer=setInterval(()=>{time--;timeEl.textContent=time;if(time<=0)finish();},1000);gameLoop();}
button.addEventListener('click',start);document.addEventListener('keydown',e=>{if(!playing)return;if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')moveBasket(basketX-6);if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')moveBasket(basketX+6);});area.addEventListener('pointermove',e=>{if(!playing)return;const r=area.getBoundingClientRect();moveBasket((e.clientX-r.left)/r.width*100);});
